# Generated by Django 4.1.7 on 2023-04-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Juan', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Juan', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Juan', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Juan', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Juan', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Juan', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Juan', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.CharField(default='Juan', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='Juan', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Juan', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='Juan', max_length=50),
        ),
    ]
