# Generated by Django 4.1.7 on 2023-04-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
